# Generated by Django 3.2.5 on 2021-08-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sample3',
            field=models.ImageField(default='', upload_to='port/images'),
        ),
    ]
