# Generated by Django 3.2.5 on 2021-08-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0002_project_sample3'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='functionalities',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='languages_used',
            field=models.TextField(default='now'),
            preserve_default=False,
        ),
    ]
