# Generated by Django 3.2.5 on 2021-08-31 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='git_link',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
