# Generated by Django 3.2.7 on 2021-09-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0005_project_git_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='live_link',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
